### ISSUE TITLE
Need customization of daemon listen port

### ISSUE THREAD

**Issue by zhanghua000** [multiverse-vcs/go-multiverse#19]
The daemon will listen TCP 9000 port, but it can't be customized, which will may result conflict between other service and multiverse daemon. I have a docker container which runs on TCP 9000 port, I have to restart it to change its port or I can't use multiverse daemon correctly. But what if someday I meet a service which can't change its port like this daemon?

**Comment by nasdf** [comment]
Closed by #20.  I'll make sure to add all of the listening ports to the config in the future.
